apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: zg8wxlz8f-python
  janus-idp.io/tekton: zg8wxlz8f-python
  backstage.io/kubernetes-id: zg8wxlz8f-python
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: zg8wxlz8f-python
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
